

services:

  database:
    image: postgres:16
    environment:
      POSTGRES_DB: desafio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./desafio-api/api
      dockerfile: Dockerfile
    environment:
      - SEU_EMAIL
      - SENHA_EMAIL
    ports:
      - '8080:8080'
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./desafio
      dockerfile: Dockerfile    
    ports:
      - '4200:4200'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:

