server:
  port: 8080
spring:
  application:
    name: application
  datasource:
    url: jdbc:postgresql://database:5432/desafio
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SEU_EMAIL}
    password: ${SENHA_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
   
    
  